### ISSUE TITLE
OpenVZ support

### ISSUE THREAD

**Issue by yswery** [outime/ipv6-dhclient-script#1]
I would love to see this being support on an OpenVZ container (mine runs on proxmox) that with a bridge interface would connect

I tried using the script but seemed the DHCP aspect might not have worked :(

**Comment by outime** [comment]
Unfortunately I've never ran Proxmox (either OVZ) in Online.net and I'm currently unable to with my kidéchire, so what I'm saying below is in theory - feel free to correct me.

Proxmox (host) shouldn't have problems regarding IPv6 as it's Debian-based. However I found out that at least the ISO provided by Online.net comes with IPv6 kernel module disabled, so you may need to enable it.

For the guests, you need to enable IPv6 forwarding in the host and set the addresses for the containers using console (vzctl) as AFAIK the web interface isn't supporting that (or at least last time I used it).

**Comment by outime** [comment]
However if it happens that you have a free machine in Online that is able to run Proxmox and you want to lend it to me for some testing I'd be glad to try making a patch for both host and guests.

**Comment by yswery** [comment]
After looking into what you said you were totally correct:

First I needed to enable the IPv6 in the proxmox module (/etc/modprobe.d/local.conf)

from 

```
options ipv6 disable=1
```

to

```
options ipv6 disable=0
```

(then rebooted)

and after added the following to /etc/sysctl.conf

```
net.ipv6.conf.default.forwarding = 1
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.proxy_ndp = 1
net.ipv6.conf.all.proxy_ndp = 1
```

followed by sysctl -p

and after doing this I am able to assign a block per OpenVZ VM with its own DUID using your script.

Cheers for the help!
