### ISSUE TITLE
Centos 6.8 not supported!

### ISSUE THREAD

**Issue by sonuyos** [outime/ipv6-dhclient-script#4]
Hello,

As 6.8 does not have systemd or systemctl, it doesnt work, any workaround?

**Comment by outime** [comment]
CentOS uses init so it'd be a matter of adapting the current calls and service config to the SysV init system. I can take a look (or anyone else) but a bit busy at the moment. As a note, this should be expected as CentOS 6.x isn't listed in the supported distros.

**Comment by outime** [comment]
I've just added CentOS 6 support in the latest commits, please check it out and reopen this issue in case of problems.
